### PR TITLE
Watch in docker

### PR DESCRIPTION
**Pull request by DavidBruant**
This is an incomplete fix to #41. Only fixes when server changes.
Looked at the browserify part. It's still unclear what the problem is and how to fix it.

### CODE REVIEW

**Comment by iOiurson** [comment]
I don't understand why this is incomplete... i tried changing server and client codes, dans it seems to work ok.

**Comment by iOiurson** [comment]
BTW
- i have resolved merge conflicts locally, should i re-PR from my account and delete this PR afterwards ?
- the separation PR #55 will have to be reviewed with regards to this PR. Up for it @DavidBruant ?

**Comment by vallettea** [comment]
thats a good news, i though the container crashed when watchify failed

**Comment by vallettea** [comment]
Also there are too many pull request hanging we should merge merge merge because I can't see where to begin

**Comment by iOiurson** [comment]
Ok it still crashes on errors for now. Maybe we'll fix this later on

**Pull request merged**
